name = "rpciege-sveltekit"
compatibility_date = "2023-05-17"

kv_namespaces = [
  { binding = "EMAILS", id = "9b0b0abb1f7a414d8dc9ac1a4aa06e29", preview_id = "" },
  { binding = "REFERRAL_CODES", id = "b0bb3daa4b994da5b4744c36ba49bc78", preview_id = "" }
]